models:
  # OpenAI模型类型
  openai:
    base_url: "https://llm.baifentan.com/openproxy/rp/v1"
    api_key: "zyb-24d7f8a7703cbae1e8bb5d205d1d06f0@quickai_test"
    models:
      - "gpt-4o"
      - "gpt-4.1-mini"

  # Anthropic模型类型
  anthropic:
    base_url: "https://llm.baifentan.com/openproxy/rp/v1"
    api_key: "zyb-24d7f8a7703cbae1e8bb5d205d1d06f0@quickai_test"
    models:
      - "claude-sonnet-4-20250514"
      - "claude-3-7-sonnet-20250219"

# 场景配置
scenes:
  task_analysis:
    model_name: "gpt-4.1-mini"
    params:
      temperature: 0.3
      max_tokens: 2000
      top_p: 0.9
    
  role_recommendation:
    model_name: "gpt-4.1-mini"
    params:
      temperature: 0.5
      max_tokens: 1500
      top_p: 0.95
    
  error_recovery:
    model_name: "gpt-4.1-mini"
    params:
      temperature: 0.2
      max_tokens: 1000
      top_p: 0.8
    
  context_compression:
    model_name: "gpt-4.1-mini"
    params:
      temperature: 0.4
      max_tokens: 800
      top_p: 0.9
    
  workflow_optimization:
    model_name: "gpt-4.1-mini"
    params:
      temperature: 0.6
      max_tokens: 1200
      top_p: 0.9
      
  main_agent:
    model_name: "gpt-4o"
    params:
      temperature: 0.7
      max_tokens: 3000
      top_p: 0.9
